# This is a basic workflow to help you get started with Actions

name: GitHub Actions Build and Deploy 10hrs10projs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: checkout

        uses: actions/checkout@master

        # 安装依赖

      - name: install

        run: yarn

        # 打包构建

      - name: build

        run: yarn build:test

        # 部署运行

      - name: Deploy

        uses: JamesIves/github-pages-deploy-action@v4.3.0

        with:

          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

          BRANCH: gh-pages

          FOLDER: dist
